---
title: "absenteeBallots"
author: "Josue Sanchez Hernandez"
format: pdf
editor: visual
---

```{r}
#| label: setup
#| include: false

library(tidyr)
library(readxl)
library(XML)
```

## Reading in Data

```{r}
# Assigning the URL of the Ohio elections website to an object
url <- "https://www.ohiosos.gov/elections/voters/about-this-election/2023-general-absenteereport/"

# Sending GET request to get webpage contents
webpage <- GET(url, add_headers('user-agent' = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'))

# Extracting links to all .xlsx files on the website
xlsx_links <- webpage |>
  read_html() |>
  html_node('.xlsx') |>
  html_text()
```

```{r}
url2 <- "https://www.ohiosos.gov/globalassets/elections/2023/gen/ohiososabreport-20231106.xlsx"

customHeaders <- c(
  "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3",
  "Accept-Language" = "en-US,en;q=0.5",
  "Accept-Encoding" = "gzip, deflate, br",
  "Accept" = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
  "Referer" = "https://www.google.com/"
  )

webpage2 <- GET(url2, add_headers(customHeaders))

print(webpage2)
```

```{r}
library(RSelenium)

rD <- rsDriver(browser = "firefox",
               chromever = NULL)
remDr <- rD$client

remDr$navigate(url)

file_links <- remDr$findElements(using = "css", value = "a[href$='.xlsx']")

getURL <- function(webElement){
    return(webElement$getElementAttribute("href")[[1]])
}

urls <- lapply(file_links, getURL)

remDr$close()  
rm(rD)
rm(remDr)

```

```{r}

for (link in 1:length(urls)) {
  rD2<- rsDriver(browser = "firefox",
               chromever = NULL)
  remDr2 <- rD2$client
  remDr2$navigate(urls[[link]])
  Sys.sleep(3)
  remDr2$close()
  rD2[["server"]]$stop()
}


```
